version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chat-app-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: chat-app-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

